### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by Vyrastas** [project-chip/zap#1060]
Tried this on both Mac (Ventura 13.4.1) and Linux (Debian 12) and get the same failure. Debug log attached.

I can use the pre-built binaries fine, but I can't build and run it locally.

```
$ npm install

> zap@0.0.0 postinstall
> electron-builder install-app-deps && husky install && npm rebuild canvas --update-binary && npm run version-stamp

  • electron-builder  version=22.14.13
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=bufferutil@4.0.7, canvas@2.11.2, sqlite3@5.1.4, utf-8-validate@5.0.10 platform=darwin arch=arm64
  ⨯ cannot execute  cause=exit status 1
                    errorOut=npm ERR! code 1
    npm ERR! path /Users/username/zap/node_modules/canvas
    npm ERR! command failed
    npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
    npm ERR! SOLINK_MODULE(target) Release/canvas-postbuild.node
    npm ERR!   CXX(target) Release/obj.target/canvas/src/backend/Backend.o
    npm ERR! Failed to execute '/Users/username/.nvm/versions/node/v16.13.2/bin/node /Users/username/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/Users/username/zap/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/username/zap/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v24.1' (1)
    npm ERR! node-pre-gyp info it worked if it ends with ok
    npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
    npm ERR! node-pre-gyp info using node@16.13.2 | darwin | arm64
    npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-electron-v24.1-darwin-unknown-arm64.tar.gz
    npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-electron-v24.1-darwin-unknown-arm64.tar.gz 
    npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and electron@24.1.3 (electron-v24.1 ABI, unknown) (falling back to source compile with node-gyp) 
    npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-electron-v24.1-darwin-unknown-arm64.tar.gz 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@8.3.0
    npm ERR! gyp info using node@16.13.2 | darwin | arm64
    npm ERR! gyp info ok 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@8.3.0
    npm ERR! gyp info using node@16.13.2 | darwin | arm64
    npm ERR! gyp info find Python using Python version 3.11.4 found at "/opt/homebrew/opt/python@3.11/bin/python3.11"
    npm ERR! gyp http GET https://electronjs.org/headers/v24.1.3/node-v24.1.3-headers.tar.gz
    npm ERR! gyp http 200 https://artifacts.electronjs.org/headers/v24.1.3/node-v24.1.3-headers.tar.gz?force_headers_dist=1
    npm ERR! gyp http GET https://electronjs.org/headers/v24.1.3/SHASUMS256.txt
    npm ERR! gyp http 200 https://artifacts.electronjs.org/headers/v24.1.3/SHASUMS256.txt?force_headers_dist=1
    npm ERR! gyp info spawn /opt/homebrew/opt/python@3.11/bin/python3.11
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/Users/username/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/Users/username/zap/node_modules/canvas/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/Users/username/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/Users/username/.electron-gyp/24.1.3/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/username/.electron-gyp/24.1.3',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/username/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/username/.electron-gyp/24.1.3/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/username/zap/node_modules/canvas',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! gyp info ok 
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@8.3.0
    npm ERR! gyp info using node@16.13.2 | darwin | arm64
    npm ERR! gyp info spawn make
    npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    npm ERR! In file included from ../src/backend/Backend.cc:1:
    npm ERR! In file included from ../src/backend/Backend.h:6:
    npm ERR! In file included from ../../nan/nan.h:60:
    npm ERR! /Users/username/.electron-gyp/24.1.3/include/node/node.h:27:2: error: "It looks like you are building this native module without using the right config.gypi.  This normally means that you need to update electron-rebuild (>=3.2.8) or node-gyp (>=9.0.0) if you're building modules directly."
    npm ERR! #error "It looks like you are building this native module without using the right config.gypi.  This normally means that you need to update electron-rebuild (>=3.2.8) or node-gyp (>=9.0.0) if you're building modules directly."
    npm ERR!  ^
    npm ERR! In file included from ../src/backend/Backend.cc:1:
    npm ERR! ../src/backend/Backend.h:60:14: warning: private field 'backend' is not used [-Wunused-private-field]
    npm ERR!     Backend* backend;
    npm ERR!              ^
    npm ERR! 1 warning and 1 error generated.
    npm ERR! make: *** [Release/obj.target/canvas/src/backend/Backend.o] Error 1
    npm ERR! gyp ERR! build error 
    npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
    npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/username/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
    npm ERR! gyp ERR! System Darwin 22.5.0
    npm ERR! gyp ERR! command "/Users/username/.nvm/versions/node/v16.13.2/bin/node" "/Users/username/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--update-binary" "--module=/Users/username/zap/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/username/zap/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v24.1"
    npm ERR! gyp ERR! cwd /Users/username/zap/node_modules/canvas
    npm ERR! gyp ERR! node -v v16.13.2
    npm ERR! gyp ERR! node-gyp -v v8.3.0
    npm ERR! gyp ERR! not ok 
    npm ERR! node-pre-gyp ERR! build error 
    npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/username/.nvm/versions/node/v16.13.2/bin/node /Users/username/.nvm/versions/node/v16.13.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --update-binary --module=/Users/username/zap/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/username/zap/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v24.1' (1)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/username/zap/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
    npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
    npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
    npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
    npm ERR! node-pre-gyp ERR! System Darwin 22.5.0
    npm ERR! node-pre-gyp ERR! command "/Users/username/.nvm/versions/node/v16.13.2/bin/node" "/Users/username/zap/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
    npm ERR! node-pre-gyp ERR! cwd /Users/username/zap/node_modules/canvas
    npm ERR! node-pre-gyp ERR! node -v v16.13.2
    npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
    npm ERR! node-pre-gyp ERR! not ok
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/username/.npm/_logs/2023-07-07T21_08_01_887Z-debug.log
    
                    command=/Users/username/.nvm/versions/node/v16.13.2/bin/node /Users/username/.nvm/versions/node/v16.13.2/lib/node_modules/npm/bin/npm-cli.js rebuild bufferutil@4.0.7 canvas@2.11.2 sqlite3@5.1.4 utf-8-validate@5.0.10
                    workingDir=
npm ERR! code 1
npm ERR! path /Users/username/zap
npm ERR! command failed
npm ERR! command sh -c electron-builder install-app-deps && husky install && npm rebuild canvas --update-binary && npm run version-stamp

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2023-07-07T21_08_01_911Z-debug.log
```

[2023-07-07T21_08_01_911Z-debug.log](https://github.com/project-chip/zap/files/11986343/2023-07-07T21_08_01_911Z-debug.log)

**Comment by turon** [comment]
Not sure what best practice is for `zap`, but in general when an `npm` project has a [package-lock.json](https://github.com/project-chip/zap/blob/master/package-lock.json), then `npm ci` is a better way to clone the dependency environment than `npm install`.

**Comment by tecimovic** [comment]
What are the versions of node and npm you run?

These are mine:
```
[~/git/zap (master)]$ npm --version
9.5.1
[~/git/zap (master)]$ node --version
v18.16.1
```

**Comment by tecimovic** [comment]
`npm ci` and `npm install` differ in the following way:
- `npm ci` will simply take what's in package-lock.json and install that.
- `npm install` will take what's in package.json, and pick the latest minor versions of those package, possibly updating package-lock.json in the process.

Generally: 
   - if you juse want to USE the product, do `npm ci`
   - if however you are developer and are willing to commit a new version of package-lock.json with latest versions, then use `npm install`.

**Comment by Vyrastas** [comment]
Thanks for the responses.  Using `npm ci` I get the same errors.

> What are the versions of node and npm you run?
> 
> These are mine:
> 
> ```
> [~/git/zap (master)]$ npm --version
> 9.5.1
> [~/git/zap (master)]$ node --version
> v18.16.1
> ```

On both machines I have:

```
$ npm --version
8.1.2
$ node --version
v16.13.2
```

Are the versions too old?

**Comment by brdandu** [comment]
> Thanks for the responses. Using `npm ci` I get the same errors.
> 
> > What are the versions of node and npm you run?
> > These are mine:
> > ```
> > [~/git/zap (master)]$ npm --version
> > 9.5.1
> > [~/git/zap (master)]$ node --version
> > v18.16.1
> > ```
> 
> On both machines I have:
> 
> ```
> $ npm --version
> 8.1.2
> $ node --version
> v16.13.2
> ```
> 
> Are the versions too old?

@Vyrastas yes I recommend moving to node v18.
Also try "npm rebuild canvas --update-binary" and what happens if you run "npm run zap"?

**Comment by Vyrastas** [comment]
Thanks everyone, I was able to get it to work by using more recent versions of npm and node.
