### ISSUE TITLE
Building failed (in venv) with `importlib.metadata.PackageNotFoundError: No package metadata was found for gyp`

### ISSUE THREAD

**Issue by reinhrst** [project-chip/zap#1097]
In a docker image (arm64) I followed the instructions on https://github.com/project-chip/zap/blob/master/docs/development-instructions.md to build. Unfortunately I ran into an error when doing `npm ci`:

```
npm ERR! gyp info spawn /matter/venv/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/matter/zap-2023.05.04/node_modules/lzma-native/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/include/nodejs/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/matter/zap-2023.05.04/node_modules/lzma-native',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
npm ERR!     return next(cls.discover(name=name))
npm ERR!            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! StopIteration
npm ERR!
npm ERR! During handling of the above exception, another exception occurred:
npm ERR!
npm ERR! Traceback (most recent call last):
npm ERR!   File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 33, in <module>
npm ERR!     sys.exit(load_entry_point('gyp==0.1', 'console_scripts', 'gyp')())
npm ERR!              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR!   File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 22, in importlib_load_entry_point
npm ERR!     for entry_point in distribution(dist_name).entry_points
npm ERR!                        ^^^^^^^^^^^^^^^^^^^^^^^
npm ERR!   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
npm ERR!     return Distribution.from_name(distribution_name)
npm ERR!            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR!   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
npm ERR!     raise PackageNotFoundError(name)
npm ERR! importlib.metadata.PackageNotFoundError: No package metadata was found for gyp
```

It took me quite some time, but in the end I found out that install fails when a python venv is active.
`deactivate`ing the venv before running `npm ci` fixed the problem.

(problem is that newer versions of ubuntu force you to make venvs, even in docker containers).

I'm not sure if (and then, where) this should be documented; so at least I wanted to put it here so that it can be found.

**Comment by paulr34** [comment]
cannot reproduce anymore

**Comment by paulr34** [comment]
please reopen if you disagree
