### ISSUE TITLE
Make XML errors easier to debug during codegen

### ISSUE THREAD

**Issue by andy31415** [project-chip/zap#1204]
We had a type error recently in two separate reasons: `uint16` used instead of `int16u` and once a type being `""` (not sure why ... maybe an erase that was never updated).

The code generator failed with very hard to debug errors like:

```
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Object.atomicType (/snapshot/zap/dist/src-electron/generator/overridable.js:63:14)
    at Object.atomicType (/snapshot/zap/dist/src-electron/generator/template-engine.js:175:31)
    at /snapshot/zap/dist/src-electron/util/zcl-util.js:545:47
    at async Promise.all (index 0)
```

Instead we should have some context on various things, in this case for example atomicType should at least tell me what type it was trying to process, so I could have seen `uint16` being at fault.

Ideally though, we should also have XML context inside types. I would have liked the trace to tell me "in foo.xml, type defined at line 123 failed to be processed" and then human review would have been much easier. As it stands we had to bisect all types one by one in XML which is very slow.

**Comment by paulr34** [comment]
@andy31415 we have XML type warnings like this 
<img width="1003" alt="Screenshot 2023-11-09 at 12 49 01 PM" src="https://github.com/project-chip/zap/assets/64710345/9902ed03-5c14-4f2f-8a45-5b22df6d0ad9">

**Comment by paulr34** [comment]
also if you click extensions you can see 
<img width="798" alt="Screenshot 2023-11-09 at 12 50 56 PM" src="https://github.com/project-chip/zap/assets/64710345/96235e7e-157b-4e58-9aee-a0e71ced9cd0">

**Comment by andy31415** [comment]
Checked offline, the existing warnings did not catch the errors in the XML I had (neither empty type nor using `uint16` instead of `int16u`)
