### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot convert null to a BigInt

### ISSUE THREAD

**Issue by Jardaliao** [project-chip/zap#1459]
### log
⇝ (node:263808) UnhandledPromiseRejectionWarning: TypeError: Cannot convert null to a BigInt
    at BigInt (<anonymous>)
    at extractBigIntegerValue (/home/jay/projects/xxx/.zap/zap-v2024.03.14-nightly-src/dist/src-electron/validation/validation.js:176:16)
    at getIntegerFromAttribute (/home/jay/projects/xxx/.zap/zap-v2024.03.14-nightly-src/dist/src-electron/validation/validation.js:214:11)
    at getBoundsInteger (/home/jay/projects/xxx/.zap/zap-v2024.03.14-nightly-src/dist/src-electron/validation/validation.js:184:20)
    at checkAttributeBoundsInteger (/home/jay/projects/xxx/.zap/zap-v2024.03.14-nightly-src/dist/src-electron/validation/validation.js:252:30)
    at validateSpecificAttribute (/home/jay/projects/xxx/.zap/zap-v2024.03.14-nightly-src/dist/src-electron/validation/validation.js:95:15)
    at /home/jay/projects/xxx/.zap/zap-v2024.03.14-nightly-src/dist/src-electron/rest/user-data.js:261:30
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:263808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:263808) UnhandledPromiseRejectionWarning: TypeError: Cannot convert null to a BigInt
    at BigInt (<anonymous>)
    at extractBigIntegerValue (/home/jay/projects/xxx/.zap/zap-v2024.03.14-nightly-src/dist/src-electron/validation/validation.js:176:16)
    at getIntegerFromAttribute (/home/jay/projects/xxx/.zap/zap-v2024.03.14-nightly-src/dist/src-electron/validation/validation.js:214:11)
    at getBoundsInteger (/home/jay/projects/xxx/.zap/zap-v2024.03.14-nightly-src/dist/src-electron/validation/validation.js:184:20)
    at checkAttributeBoundsInteger (/home/jay/projects/xxx/.zap/zap-v2024.03.14-nightly-src/dist/src-electron/validation/validation.js:252:30)
    at validateSpecificAttribute (/home/jay/projects/xxx/.zap/zap-v2024.03.14-nightly-src/dist/src-electron/validation/validation.js:95:15)
    at /home/jay/projects/xxx/.zap/zap-v2024.03.14-nightly-src/dist/src-electron/rest/user-data.js:261:30
(node:263808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

### how to reproduce:

- clone connecthomeip v1.3
- source scripts/activate.sh
- ./scripts/tools/zap/zap_download.py --zap=SOURCE
- export ZAP_DEVELOPMENT_PATH=./.zap/zap-v2024.03.14-nightly-src
- ./scripts/tools/zap/run_zaptool.sh ./examples/bridge-app/bridge-common/bridge-app.zap
- enable `EventList` or `AttributeList` attribute of Switch Cluster on endpoint 2

**Comment by dhchandw** [comment]
`EventList` and `AttributeList` are externally managed attributes and should not be visible in the ZAP GUI. If you pull the latest ZAP version you will not see these attributes. These attributes are managed in the application code.

**Comment by JZ-ZZY** [comment]
> `EventList` and `AttributeList` are externally managed attributes and should not be visible in the ZAP GUI. If you pull the latest ZAP version you will not see them. These attributes are managed in the application code.

Hi, I met a same issue in Occupancy Sensor Cluster, Featuremap attribute.When creating this cluster in zap-ui, the featuremap attribute is automatically created as External storage, and I am unable to set its value in the UI. Zap tip will quote UnhandledPromiseRejectionWarning: TypeError: always convert a null to a BigInt error, even though I have changed the local zap file, still can't solve the problem. May I ask if there is any way  to solve it?
