### ISSUE TITLE
zap unable to safe new configuration into a .zap file

### ISSUE THREAD

**Issue by eve-cxrp** [project-chip/zap#155]
After editing a .zap file through the ui I get the following error message:

```
{"level":40,"time":1621490551426,"pid":55329,"hostname":"meows-iMac.local","name":"zap","msg":"HTTP server exception.","err":{"type":"TypeError","message":"browserApi.executeSave is not a function","stack":"TypeError: browserApi.executeSave is not a function\n    at fileSave (/Users/meow/Prog/chip/eve-ncs-chip/external/zap/src-electron/ui/menu.js:313:14)\n    at doSave (/Users/meow/Prog/chip/eve-ncs-chip/external/zap/src-electron/ui/menu.js:252:5)\n    at click (/Users/meow/Prog/chip/eve-ncs-chip/external/zap/src-electron/ui/menu.js:52:11)\n    at MenuItem.click (electron/js2c/browser_init.js:73:1742)\n    at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)","alert":"⛔"}}
{"level":50,"time":1621490551426,"pid":55329,"hostname":"meows-iMac.local","name":"zap","msg":{"alert":"⛔"}}
```

And the file is not updated.

**Comment by tecimovic** [comment]
This is all fixed on a master branch by now.

**Comment by eve-cxrp** [comment]
I still see the following error:

```
{"level":50,"time":1622040654554,"pid":85940,"hostname":"meow","name":"zap","msg":"Unable to save project with sessionId(1)"}
{"level":50,"time":1622040654554,"pid":85940,"hostname":"meow","name":"zap","msg":{"errno":-2,"code":"ENOENT","syscall":"open","path":""}}
```

I try to edit a zap file in the following manner:

```
node ./src-script/zap-start.js --logToStdout -z $ZCL_JSON -g $APP_TEMPLATES_JSON -i "$OPT_IN_FILE"
```
