### ISSUE TITLE
Running error: UnhandledPromiseRejectionWarning:   SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by HeFeng1947** [project-chip/zap#325]
I use ubuntu 21.10. I tried to install it all day and it didn't work
My npm version: 6.14.14
My node version: 14.17.5
My installing output log as follow:
```shell
$ npm ci
npm WARN prepare removing existing node_modules/ before installation

> fast-xml-parser@3.17.5 postinstall /home/iot/workspace/matter/zap/node_modules/fast-xml-parser
> node tasks/postinstall.js || exit 0

Love fast-xml-parser? Check https://amitkumargupta.work for more projects and contribution.


> utf-8-validate@5.0.5 install /home/iot/workspace/matter/zap/node_modules/utf-8-validate
> node-gyp-build


> sqlite3@5.0.2 install /home/iot/workspace/matter/zap/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/home/iot/workspace/matter/zap/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node" is installed via remote

> core-js@3.15.2 postinstall /home/iot/workspace/matter/zap/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> canvas@2.8.0 install /home/iot/workspace/matter/zap/node_modules/canvas
> node-pre-gyp install --fallback-to-build

[canvas] Success: "/home/iot/workspace/matter/zap/node_modules/canvas/build/Release/canvas.node" is installed via remote

> bufferutil@4.0.3 install /home/iot/workspace/matter/zap/node_modules/bufferutil
> node-gyp-build


> lzma-native@8.0.1 install /home/iot/workspace/matter/zap/node_modules/lzma-native
> node-gyp-build


> fs-xattr@0.3.1 install /home/iot/workspace/matter/zap/node_modules/fs-xattr
> node-gyp rebuild

make: 进入目录“/home/iot/workspace/matter/zap/node_modules/fs-xattr/build”
  CC(target) Release/obj.target/xattr/src/async.o
  CC(target) Release/obj.target/xattr/src/error.o
  CC(target) Release/obj.target/xattr/src/sync.o
  CC(target) Release/obj.target/xattr/src/util.o
  CC(target) Release/obj.target/xattr/src/xattr.o
  SOLINK_MODULE(target) Release/obj.target/xattr.node
  COPY Release/xattr.node
make: 离开目录“/home/iot/workspace/matter/zap/node_modules/fs-xattr/build”

> macos-alias@0.2.11 install /home/iot/workspace/matter/zap/node_modules/macos-alias
> node-gyp rebuild

make: 进入目录“/home/iot/workspace/matter/zap/node_modules/macos-alias/build”
  CXX(target) Release/obj.target/volume/src/volume.o
../src/volume.cc:9:2: error: #error This platform is not implemented yet
    9 | #error This platform is not implemented yet
      |  ^~~~~
In file included from ../src/volume.cc:2:
../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../nan/nan.h:2298:7: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2298 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/volume.cc: In function ‘void Initialize(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/volume.cc:16:49: error: ‘MethodGetVolumeName’ was not declared in this scope
   16 |     Nan::GetFunction(Nan::New<FunctionTemplate>(MethodGetVolumeName)).ToLocalChecked());
      |                                                 ^~~~~~~~~~~~~~~~~~~
In file included from ../../nan/nan.h:54,
                 from ../src/volume.cc:2:
../src/volume.cc: At global scope:
/home/iot/.cache/node-gyp/14.17.5/include/node/node.h:758:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  758 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/iot/.cache/node-gyp/14.17.5/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
  792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/volume.cc:19:1: note: in expansion of macro ‘NODE_MODULE’
   19 | NODE_MODULE(volume, Initialize)
      | ^~~~~~~~~~~
make: *** [volume.target.mk:111：Release/obj.target/volume/src/volume.o] 错误 1
make: 离开目录“/home/iot/workspace/matter/zap/node_modules/macos-alias/build”
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.8.0-63-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/iot/workspace/matter/zap/node_modules/macos-alias
gyp ERR! node -v v14.17.5
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> electron@12.2.2 postinstall /home/iot/workspace/matter/zap/node_modules/electron
> node install.js


> highlight.js@9.18.5 postinstall /home/iot/workspace/matter/zap/node_modules/highlight.js
> node deprecated.js

-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

  Verion 9 of Highlight.js has reached EOL.  It will no longer
  be supported or receive security updates in the future.
  Please upgrade to version 10 or encourage your indirect
  dependencies to do so.

  For more info:
  
  https://github.com/highlightjs/highlight.js/issues/2877
  https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md
 
-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

> core-js@2.6.12 postinstall /home/iot/workspace/matter/zap/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> deasync@0.1.21 install /home/iot/workspace/matter/zap/node_modules/deasync
> node ./build.js

`linux-x64-node-14` exists; testing
Binary is fine; exiting

> ejs@2.7.4 postinstall /home/iot/workspace/matter/zap/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> core-js@2.6.12 postinstall /home/iot/workspace/matter/zap/node_modules/@babel/runtime-corejs2/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> zap@2021.11.16 postinstall /home/iot/workspace/matter/zap
> electron-builder install-app-deps && husky install && npm rebuild canvas --update-binary

  • electron-builder  version=22.11.7
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=bufferutil@4.0.3, canvas@2.8.0, sqlite3@5.0.2, utf-8-validate@5.0.5 platform=linux arch=x64
husky - Git hooks installed

> canvas@2.8.0 install /home/iot/workspace/matter/zap/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[canvas] Success: "/home/iot/workspace/matter/zap/node_modules/canvas/build/Release/canvas.node" is installed via remote
canvas@2.8.0 /home/iot/workspace/matter/zap/node_modules/canvas
added 3230 packages in 120.504s

```

And my running log as follow:
```shell
$ npm run zap

> zap@2021.11.16 zap /home/iot/workspace/matter/zap
> node src-script/zap-start.js --logToStdout --gen ./test/gen-template/zigbee/gen-templates.json

🚀 Executing: git log -1 --format={"hash": "%H","timestamp": %ct}
🔍 Git commit: 4514fb5e12533bb3447f93e2774421c8537ed854 from Tue Nov 23 2021 23:47:58 GMT+0800 (中国标准时间)
🔍 Current src hash: 2wLh2+SuWoBS4NaaY9ieQNGfsb8=
🔍 Current src-shared hash: 6r/XRrNXSM38C5D7KoQ0xw3U0J4=
👎 Error reading old hash file: /home/iot/workspace/matter/zap/spa/hash.json
🐝 Front-end code changed, so we need to rebuild SPA.
🚀 Executing: npx quasar build

 Build mode........ spa
 Pkg quasar........ v1.16.0
 Pkg @quasar/app... v3.2.3
 Pkg webpack....... v5
 Debugging......... no
 Publishing........ no

 Configured browser support (>= 47.10% of global marketshare):
 · Chrome for Android >= 95
 · Firefox for Android >= 92
 · QQ for Android >= 10.4
 · UC for Android >= 12.12
 · Android >= 95
 · Baidu >= 7.12
 · Chrome >= 96
 · Edge >= 95
 · Firefox >= 94
 · IE >= 11
 · iOS >= 15
 · Kaios >= 2.5
 · Opera Mini >= all
 · Opera Mobile >= 64
 · Opera >= 81
 · Safari >= 15.1
 · Samsung >= 15.0

 App • Running "@quasar/testing" Quasar App Extension...
 App • Running "@quasar/testing-unit-jest" Quasar App Extension...
⇝ (node:76702) UnhandledPromiseRejectionWarning:   SyntaxError: Unexpected token u in JSON at position 0
  
  - JSON.parse
  
  - quasar-conf-file.js:30 clone
    [zap]/[@quasar]/app/lib/quasar-conf-file.js:30:15
  
  - quasar-conf-file.js:403 QuasarConfFile.compile
    [zap]/[@quasar]/app/lib/quasar-conf-file.js:403:29
  
  - quasar-build:181 async build
    [zap]/[@quasar]/app/bin/quasar-build:181:3
  

(Use `node --trace-warnings ...` to show where the warning was created)
(node:76702) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
⇝ (node:76702) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
✍ Writing out new hash file.
[Error: ENOENT: no such file or directory, open '/home/iot/workspace/matter/zap/spa/hash.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/iot/workspace/matter/zap/spa/hash.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zap@2021.11.16 zap: `node src-script/zap-start.js --logToStdout --gen ./test/gen-template/zigbee/gen-templates.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zap@2021.11.16 zap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iot/.npm/_logs/2021-11-24T06_46_01_502Z-debug.log

```

Debug log as follow:
```
cat /home/iot/.npm/_logs/2021-11-24T06_46_01_502Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'zap' ]
2 info using npm@6.14.14
3 info using node@v14.17.5
4 verbose run-script [ 'prezap', 'zap', 'postzap' ]
5 info lifecycle zap@2021.11.16~prezap: zap@2021.11.16
6 info lifecycle zap@2021.11.16~zap: zap@2021.11.16
7 verbose lifecycle zap@2021.11.16~zap: unsafe-perm in lifecycle true
8 verbose lifecycle zap@2021.11.16~zap: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/iot/workspace/matter/zap/node_modules/.bin:/home/iot/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle zap@2021.11.16~zap: CWD: /home/iot/workspace/matter/zap
10 silly lifecycle zap@2021.11.16~zap: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'node src-script/zap-start.js --logToStdout --gen ./test/gen-template/zigbee/gen-templates.json'
10 silly lifecycle ]
11 silly lifecycle zap@2021.11.16~zap: Returned: code: 1  signal: null
12 info lifecycle zap@2021.11.16~zap: Failed to exec zap script
13 verbose stack Error: zap@2021.11.16 zap: `node src-script/zap-start.js --logToStdout --gen ./test/gen-template/zigbee/gen-templates.json`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid zap@2021.11.16
15 verbose cwd /home/iot/workspace/matter/zap
16 verbose Linux 5.8.0-63-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "zap"
18 verbose node v14.17.5
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 1
22 error zap@2021.11.16 zap: `node src-script/zap-start.js --logToStdout --gen ./test/gen-template/zigbee/gen-templates.json`
22 error Exit status 1
23 error Failed at the zap@2021.11.16 zap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

I've tried everything in FAQ and nothing works. What should I do next?

**Comment by jingteng25742** [comment]
@HeFeng1947 
ZAP has been updated with many fixes since the creation of the ticket. 
Are you still running into the build issue with the latest ZAP?
Currently, there are also binary version of ZAP available the link below as well:

https://github.com/project-chip/zap/actions/workflows/release.yml

**Comment by brdandu** [comment]
@HeFeng1947 following up on @jingteng25742's comment. Can I close this issue?

**Comment by vindicatorr** [comment]
I can say I've encountered this `lzma-native` build issue as well, so you may want to re-open it... or maybe not. Before submitting this, I noticed `node_modules` wasn't being "git clean"ed, and I saw it was in `.gitignore`.
I deleted `node_modules`, and `npm install`ed again, and it worked it's way through.
*****
I saw https://github.com/nodejs/node-gyp/issues/2347, but that didn't fix the issue.

Commit: c0a2dfc986db47cbfba9d470df59c1b0d0925874

```
1735 error node-pre-gyp WARN Pre-built binaries not installable for lzma-native@6.0.1 and node@16.14.2 (node-v93 ABI, glibc) (falling back to source compile with node-gyp) 
1735 error node-pre-gyp WARN Hit error bad download 
1735 error gyp info it worked if it ends with ok
1735 error gyp info it worked if it ends with ok
1735 error gyp info using node-gyp@9.3.1
1735 error gyp info using node@16.14.2 | linux | x64
1735 error gyp info using node-gyp@9.3.1
1735 error gyp info using node@16.14.2 | linux | x64
1735 error gyp info ok 
1735 error gyp info ok 
1735 error gyp info it worked if it ends with ok
1735 error gyp info it worked if it ends with ok
1735 error gyp info using node-gyp@9.3.1
1735 error gyp info using node@16.14.2 | linux | x64
1735 error gyp info using node-gyp@9.3.1
1735 error gyp info using node@16.14.2 | linux | x64
1735 error gypgyp info  info find Python using Python version 3.10.9 found at "/usr/bin/python3"
1735 error find Python using Python version 3.10.9 found at "/usr/bin/python3"
1735 error gyp info spawn /usr/bin/python3
1735 error gyp info spawn args [
1735 error gyp info spawn args   '<pathTo>/node_env16/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
1735 error gyp info spawn args   'binding.gyp',
1735 error gyp info spawn args   '-f',
1735 error gyp info spawn args   'make',
1735 error gyp info spawn args   '-I',
1735 error gyp info spawn args   '<pathTo>/zap/node_modules/lzma-native/build/config.gypi',
1735 error gyp info spawn args   '-I',
1735 error gyp info spawn args   '<pathTo>/node_env16/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
1735 error gyp info spawn args   '-I',
1735 error gyp info spawn args   '<pathTo>/.cache/node-gyp/16.14.2/include/node/common.gypi',
1735 error gyp info spawn args   '-Dlibrary=shared_library',
1735 error gyp info spawn args   '-Dvisibility=default',
1735 error gyp info spawn args   '-Dnode_root_dir=<pathTo>/.cache/node-gyp/16.14.2',
1735 error gyp info spawn args   '-Dnode_gyp_dir=<pathTo>/node_env16/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp',
1735 error gyp info spawn args   '-Dnode_lib_file=<pathTo>/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
1735 error gyp info spawn args   '-Dmodule_root_dir=<pathTo>/zap/node_modules/lzma-native',
1735 error gyp info spawn args   '-Dnode_engine=v8',
1735 error gyp info spawn args   '--depth=.',
1735 error gyp info spawn args   '--no-parallel',
1735 error gyp info spawn args   '--generator-output',
1735 error gyp info spawn args   'build',
1735 error gyp info spawn args   '-Goutput_dir=.'
1735 error gyp info spawn args ]
1735 error gyp info spawn /usr/bin/python3
1735 error gyp info spawn args [
1735 error gyp info spawn args   '<pathTo>/node_env16/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
1735 error gyp info spawn args   'binding.gyp',
1735 error gyp info spawn args   '-f',
1735 error gyp info spawn args   'make',
1735 error gyp info spawn args   '-I',
1735 error gyp info spawn args   '<pathTo>/zap/node_modules/lzma-native/build/config.gypi',
1735 error gyp info spawn args   '-I',
1735 error gyp info spawn args   '<pathTo>/node_env16/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
1735 error gyp info spawn args   '-I',
1735 error gyp info spawn args   '<pathTo>/.cache/node-gyp/16.14.2/include/node/common.gypi',
1735 error gyp info spawn args   '-Dlibrary=shared_library',
1735 error gyp info spawn args   '-Dvisibility=default',
1735 error gyp info spawn args   '-Dnode_root_dir=<pathTo>/.cache/node-gyp/16.14.2',
1735 error gyp info spawn args   '-Dnode_gyp_dir=<pathTo>/node_env16/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp',
1735 error gyp info spawn args   '-Dnode_lib_file=<pathTo>/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
1735 error gyp info spawn args   '-Dmodule_root_dir=<pathTo>/zap/node_modules/lzma-native',
1735 error gyp info spawn args   '-Dnode_engine=v8',
1735 error gyp info spawn args   '--depth=.',
1735 error gyp info spawn args   '--no-parallel',
1735 error gyp info spawn args   '--generator-output',
1735 error gyp info spawn args   'build',
1735 error gyp info spawn args   '-Goutput_dir=.'
1735 error gyp info spawn args ]
1735 error gyp: Call to 'sh liblzma-config.sh "<pathTo>/zap/node_modules/lzma-native/build" "<pathTo>/zap/node_modules/lzma-native/deps/xz-5.2.3.tar.bz2"' returned exit status 77 while in binding.gyp. while trying to load binding.gyp
1735 error gyp ERR! configure error 
1735 error gyp ERR! stack Error: `gyp` failed with exit code: 1
1735 error gyp ERR! stack     at ChildProcess.onCpExit (<pathTo>/node_env16/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/configure.js:325:16)
1735 error gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
1735 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
1735 error gyp ERR! System Linux 6.2.1-dirty
1735 error gyp ERR! command "<pathTo>/node_env16/bin/node" "<pathTo>/node_env16/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=<pathTo>/zap/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=<pathTo>/zap/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
1735 error gyp ERR! cwd <pathTo>/zap/node_modules/lzma-native
1735 error gyp ERR! node -v v16.14.2
1735 error gyp ERR! node-gyp -v v9.3.1
1735 error gyp ERR! not ok 
1735 error node-pre-gyp ERR! build error 
1735 error node-pre-gyp ERR! stack Error: Failed to execute '<pathTo>/node_env16/bin/node <pathTo>/node_env16/lib/node_modules/npm/node_modules/@npmcli/run-script/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=<pathTo>/zap/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64/lzma_native.node --module_name=lzma_native --module_path=<pathTo>/zap/node_modules/lzma-native/binding-v6.0.1-n-api-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
1735 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (<pathTo>/zap/node_modules/lzma-native/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
1735 error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
1735 error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
1735 error node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
1735 error node-pre-gyp ERR! System Linux 6.2.1-dirty
1735 error node-pre-gyp ERR! command "<pathTo>/node_env16/bin/node" "<pathTo>/zap/node_modules/lzma-native/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
1735 error node-pre-gyp ERR! cwd <pathTo>/zap/node_modules/lzma-native
1735 error node-pre-gyp ERR! node -v v16.14.2
1735 error node-pre-gyp ERR! node-pre-gyp -v v0.11.0
1735 error node-pre-gyp ERR! not ok 
1735 error gyp info ok
```
