### ISSUE TITLE
Toggling storage option is broken

### ISSUE THREAD

**Issue by tecimovic** [project-chip/zap#339]
1. Go to any attribute.
2. Toggle the "Storage option" dropdown.
3. Observe:
```
⇝ (node:59858) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at /Users/fesseha/Sources/connectedhomeipfork/third_party/zap/repo/src-electron/rest/user-data.js:189:26
    at Layer.handle [as handle_request] (/Users/fesseha/Sources/connectedhomeipfork/third_party/zap/repo/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/fesseha/Sources/connectedhomeipfork/third_party/zap/repo/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/fesseha/Sources/connectedhomeipfork/third_party/zap/repo/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/fesseha/Sources/connectedhomeipfork/third_party/zap/repo/node_modules/express/lib/router/layer.js:95:5)
    at /Users/fesseha/Sources/connectedhomeipfork/third_party/zap/repo/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/fesseha/Sources/connectedhomeipfork/third_party/zap/repo/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/fesseha/Sources/connectedhomeipfork/third_party/zap/repo/node_modules/express/lib/router/index.js:275:10)
    at /Users/fesseha/Sources/connectedhomeipfork/third_party/zap/repo/src-electron/server/http-server.js:212:11
⇝ (node:59858) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 52)
```

**Comment by jmartinez-silabs** [comment]
Same happens for assigning a default value to an attribute.

You can write the desired value in the text box. But once you click elsewhere,it reverts back to 0

```
⇝ (node:87101) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at /Users/GitHub/connectedhomeip/third_party/zap/repo/src-electron/rest/user-data.js:189:26
    at Layer.handle [as handle_request] (/Users/GitHub/connectedhomeip/third_party/zap/repo/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/GitHub/connectedhomeip/third_party/zap/repo/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/GitHub/connectedhomeip/third_party/zap/repo/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/GitHub/connectedhomeip/third_party/zap/repo/node_modules/express/lib/router/layer.js:95:5)
    at /Users/GitHub/connectedhomeip/third_party/zap/repo/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/GitHub/connectedhomeip/third_party/zap/repo/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/GitHub/connectedhomeip/third_party/zap/repo/node_modules/express/lib/router/index.js:275:10)
    at /Users/GitHub/connectedhomeip/third_party/zap/repo/src-electron/server/http-server.js:212:11
(node:87101) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 88)
```

**Comment by jonsmirl** [comment]
The XML needs a 'strorage' option so that the storage class can be properly defaulted.
