### ISSUE TITLE
ZAP Electron GUI is failing to open on MacOS

### ISSUE THREAD

**Issue by rochaferraz** [project-chip/zap#378]
Matter TE6 branch works fine
Matter TE7.5 (1c2091bfa2) throws the following logs on MacOS. It only opens an empty electron page. Works fine on Linux.

Node v16.13.1
Node modules updated with `npm update`

```
➜  matter git:(branch) ✗ scripts/tools/zap/run_zaptool.sh
🚀 Executing: git log -1 --format={"hash": "%H","timestamp": %ct}
🔍 Git commit: <...> from Mon Sep 20 2021 10:19:37 GMT-0300 (Brasilia Standard Time)
🔍 Current src hash: huCqi7Fk1OdKoLDQG9k2LfGClVs=
🔍 Current src-shared hash: IAxPhOE5IxuoxP9BxaHE6IsiI5s=
🔍 Previous src hash: huCqi7Fk1OdKoLDQG9k2LfGClVs=
🔍 Previous src-shared hash: IAxPhOE5IxuoxP9BxaHE6IsiI5s=
👍 There were no changes to front-end code, so we don't have to rebuild the SPA.
🚀 Executing: npm run build-backend

> zap@0.99.6 build-backend
> npx tsc --build ./tsconfig.json

🚀 Executing: npx electron dist/src-electron/main-process/electron-main.js --logToStdout --gen /Users/rochaferraz/matter/src/app/zap-templates/app-templates.json --zcl /Users/xx/matter/src/app/zap-templates/zcl/zcl.json
{"level":50,"time":1642634432585,"pid":86945,"hostname":"xyz","name":"zap","msg":{"errno":19,"code":"SQLITE_CONSTRAINT"},"err":{"alert":""}}
{"level":50,"time":1642634432586,"pid":86945,"hostname":"xyz","name":"zap","msg":{"errno":19,"code":"SQLITE_CONSTRAINT"},"err":{"alert":""}}
⇝ (node:86945) UnhandledPromiseRejectionWarning: Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: TAG.PACKAGE_REF, TAG.NAME
(Use `Electron --trace-warnings ...` to show where the warning was created)
⇝ (node:86945) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:86945) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{"level":30,"time":1642634455798,"pid":86945,"hostname":"xyz","name":"zap","msg":"Activate...","err":{"alert":""}}
⇝ (node:86945) UnhandledPromiseRejectionWarning: Error: ERR_CONNECTION_REFUSED (-102) loading 'http://localhost:9070/?'
    at rejectAndCleanup (electron/js2c/browser_init.js:217:1457)
    at Object.failListener (electron/js2c/browser_init.js:217:1670)
    at Object.emit (events.js:315:20)
⇝ (node:86945) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
{"level":30,"time":1642634456345,"pid":86945,"hostname":"xyz","name":"zap","msg":"Activate...","err":{"alert":""}}
```

**Comment by tecimovic** [comment]
Huh? Is it possible you have another stray copy running somewhere? We'll have to investigate this...

**Comment by rochaferraz** [comment]
Thanks for the prompt answer Timotej.

Nope. Nothing related to electron/node/zap shows in `ps`, I even rebooted to be sure

**Comment by jingteng25742** [comment]
@rochaferraz 
I just checked out commit#1c2091bfa2 and zap was able to be launched via scripts/tools/zap/run_zaptool.sh
Can try following? 
 1) updating/making sure your "zap" repo was updated properly.
     I see commit#d22a17a5 is the corresponding submodule pointer for ZAP. 
  2) running 'git clean -ffdx' under zap repo
  3) try run_zaptool.sh again

ENV: 
os: mac catalina
node: 16.13.2

**Comment by rochaferraz** [comment]
My commit was in fact outdated, and was not #d22a17a5 (I'm on a branch). When I rebased to master it didn't change the zap repo it should be pointing to.

Thanks & closing
