### ISSUE TITLE
Add ZAP CLI binary to GitHub Build artifacts and fix ZAP CLI binary. 

### ISSUE THREAD

**Issue by DennisJensen95** [project-chip/zap#526]
I would like the ZAP CLI binary executable available on GitHub artifacts. 
This allows using the ZAP binary in a headless mode. 

In addition, the current ZAP CLI binary does not work on Linux and Windows. It produces the following below error:
```
Error: Cannot find module '/snapshot/zap/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node'
Require stack:
- /snapshot/zap/node_modules/sqlite3/lib/sqlite3-binding.js
- /snapshot/zap/node_modules/sqlite3/lib/sqlite3.js
- /snapshot/zap/dist/src-electron/db/db-api.js
- /snapshot/zap/dist/src-electron/main-process/startup.js
- /snapshot/zap/dist/src-electron/main-process/main.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1819:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/zap/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) 
```

**Comment by jingteng25742** [comment]
@DennisJensen95 
The zap-cli binaries are packaged within the .zip assets. 
I'm closing the ticket for now. Feel free to re-open if you run into any issues.
