### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by rcasallas-silabs** [project-chip/zap#935]
TypeError: Cannot read properties of undefined (reading 'includes') [line: 50, column: 36, file: /git/matter/examples/lighting-app/silabs/efr32/third_party/connectedhomeip/src/app/zap-templates/templates/app/endpoint_config.zapt ]
    at /snapshot/zap/dist/src-electron/generator/matter/app/zap-templates/templates/app/helper.js
    at Array.forEach (<anonymous>)
    at Object.chip_endpoint_generated_functions (/snapshot/zap/dist/src-electron/generator/matter/app/zap-templates/templates/app/helper.js)
    at Object.w (/snapshot/zap/dist/src-electron/generator/template-engine.js)
    at Object.helperWrapper (/snapshot/zap/node_modules/promised-handlebars/index.js:130:23)
    at Object.<anonymous> (/snapshot/zap/node_modules/promised-handlebars/lib/utils.js:29:28)
    at Object.wrapper (/snapshot/zap/node_modules/handlebars/lib/handlebars/internal/wrapHelper.js:10:19)
    at eval (eval at createFunctionContext (/snapshot/zap/node_modules/handlebars/lib/handlebars/compiler/javascript-compiler.js:265:23), <anonymous>:28:252)
    at Object.prog (/snapshot/zap/node_modules/handlebars/lib/handlebars/runtime.js:333:12)
    at Object.prepareAndResolveMarkers (/snapshot/zap/node_modules/promised-handlebars/index.js:99:39)
🕐 Generation time: 1s 436ms
{"endpoint_config.h":{}}
Error: Generation failed: /git/matter/examples/lighting-app/silabs/efr32/third_party/connectedhomeip/examples/lighting-app/silabs/efr32/data_model/lighting-thread-app.zap
    at generateSingleFile (/snapshot/zap/dist/src-electron/main-process/startup.js)
    at startGeneration (/snapshot/zap/dist/src-electron/main-process/startup.js)
Zap generation error: Error: Generation failed: /git/matter/examples/lighting-app/silabs/efr32/third_party/connectedhomeip/examples/lighting-app/silabs/efr32/data_model/lighting-thread-app.zap
Searching for zcl file from /git/matter/examples/lighting-app/silabs/efr32/third_party/connectedhomeip/examples/lighting-app/silabs/efr32/data_model/lighting-thread-app.zap

**Comment by paulr34** [comment]
@rcasallas-silabs closed this with a fix and it was reopened without explanation
